### PR TITLE
Remove nodejs dependency

### PR DESCRIPTION
**Pull request by Akianonymus**

### CODE REVIEW

**Comment by KevCui** [comment]
Thanks for your pull request and sharing the method to replace `nodejs` dependency.

It's indeed an interesting idea. However, as you mentioned in the comment, the hard-coded URL structure is not flexible to adapt the different URL structures. For example, some files may be hosted on the other file servers.

Moreover, `nodejs` is quite popular nowadays. Many, if not majority, already installed it and used it on their machines. Keeping `nodejs` as a dependency shouldn't be a heavy burden for the users.

Therefore, I will not merge this pull request with the current state. I hope this decision is fine for you as well. Thanks again for your time and your idea.

**Comment by Akianonymus** [comment]
@KevCui Well, can you link some urls where it doesn't work, i could implement it more efficiently.

**Comment by Akianonymus** [comment]
@KevCui Well, i agree with what you are saying.

But i just tested all of their database, atleast 1st episode of every anime available there, it works.

This is the code snippet i used..

```
# form slugs list
grep -o '\[.*\]' anime.list | sed -e "s/^\[//g" -e "s/\].*$//g" >| slugs

# get link of first episode of every slug
xargs -n 1 -P 100 -I {} bash -c '                        
bash animepahe-dl.sh -s "{}" -l -e 1 || echo {} 1>&2
sleep 2                                           
' < slugs 1>| success 2>| error

# do a head request to images link and grab the http code
xargs -n 1 -P 100 -I {} bash -c '
curl -s -I {} -e "https://kwik.cx/" | head -n 1 || echo {}
sleep 1
' < slugs 1>| all_logs 2>&1

# if this outputs anything, means some error present
grep -v "HTTP/2 20" all_logs

# clear all files
rm -f slugs success error all_logs
```

This fetches the link of episode 1 of every slug ( wherever available ), then does a head request with curl to see if response was good.

Test it yourself. I don't think this pr should be a problem anymore.

**Comment by KevCui** [comment]
Hi @Akianonymus I appreciate your effort on checking the links.

The method might work well on current service state for now. However, the point is that this fixed URL structure may not work if the method of js obfuscation changes or the file sever host changes... Those assumptions may or may not happen,  since I don't have an overview and the control of the service itself. But for any cases, I'd prefer to using `nodejs` because it's more likely to keep working, even when those presumable cases may happen.

**Comment by Akianonymus** [comment]
@KevCui Well, you still make sense but just equally flawed.

Maybe a a change will come which will change where the js obfuscation is present, making the script unable to grab the js code to execute.

Nonetheless, you are right, just relying on my method is just downgrading the script.

How about this, keep both, if node is not present, then use bash native method.

If bash native method fails, then print to the user to install nodejs and try again.

**Comment by KevCui** [comment]
Hi @Akianonymus As I mentioned above, I don't see installing `nodejs` is a heavy burden for the users. If let me choose to install `nodejs` or make code a bit complex, I'd choose the former. Sorry about that.

**Comment by Akianonymus** [comment]
@KevCui Hmm, no worries.

**Pull request closed without merging**
