### PR TITLE
dl: start treating FFmpeg parsing method as fallback

### PR DESCRIPTION
**Pull request by djchittoor**
This is the first step for making the paralleling download
implementation as the norm for downloading media from animepahe

Signed-off-by: Daniel Jacob Chittoor <djchittoor47@gmail.com>

### CODE REVIEW

**Comment by djchittoor** [comment]
As I mentioned before in our previous thread, I plan on making the parallel downloading the norm for downloading media from animepahe and this commit is the first step in the patchset, Please change functions name or variables as per Owner's wish

**Comment by KevCui** [comment]
Hi @djchittoor tbh, I don't see too much value of this commit at this moment. Do you have more changes to push into this merge request? It would make more sense to make a common ffmpeg paring method for both download mechanisms.

**Comment by djchittoor** [comment]
> Hi @djchittoor tbh, I don't see too much value of this commit at this moment. Do you have more changes to push into this merge request? It would make more sense to make a common ffmpeg paring method for both download mechanisms.

Yes, I do have, If you can please do that common ffmepg paring

**Comment by djchittoor** [comment]
Close this for now till I complete the whole fallback thing

**Pull request closed without merging**
